unstable_features = true
version = "Two"

newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Unstable features
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
wrap_comments = true

