[cargo-new]
vcs = "none"

[profile.release]
lto = "thin"
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Ctarget-cpu=native", "-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]
